package org.studia.barterapplication.models;

import java.util.ArrayList;

/**
 * Offer is generated by users to propose items exchange to another user
 */

public class Offer {

    //Properties
    String id;
    String senderId;
    String receiverId;
    ArrayList<StringWithKey> senderItems;
    int senderCash;
    ArrayList<StringWithKey> receiverItems;
    int receiverCash;
    String offerStatus;


    public Offer() {
    }

    //Constructors
    public Offer(String id, String senderId, String receiverId, ArrayList<StringWithKey> senderItems, int senderCash, ArrayList<StringWithKey> receiverItems, int receiverCash, String offerStatus) {
        this.id = id;
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.senderItems = senderItems;
        this.senderCash = senderCash;
        this.receiverItems = receiverItems;
        this.receiverCash = receiverCash;
        this.offerStatus = offerStatus;
    }

    // getters
    public String getId() {
        return id;
    }

    public String getSenderId() {
        return senderId;
    }

    public String getReceiverId() {
        return receiverId;
    }

    public ArrayList<StringWithKey> getSenderItems() {
        return senderItems;
    }

    public int getSenderCash() {
        return senderCash;
    }

    public ArrayList<StringWithKey> getReceiverItems() {
        return receiverItems;
    }

    public int getReceiverCash() {
        return receiverCash;
    }

    public String getOfferStatus() {
        return offerStatus;
    }


    // setters
    public void setId(String id) {
        this.id = id;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    public void setSenderItems(ArrayList<StringWithKey> senderItems) {
        this.senderItems = senderItems;
    }

    public void setSenderCash(int senderCash) {
        this.senderCash = senderCash;
    }

    public void setReceiverItems(ArrayList<StringWithKey> receiverItems) {
        this.receiverItems = receiverItems;
    }

    public void setReceiverCash(int receiverCash) {
        this.receiverCash = receiverCash;
    }

    public void setOfferStatus(String offerStatus) {
        this.offerStatus = offerStatus;
    }

    @Override
    public String toString() {
        return "Offer{" +
                "id='" + id + '\'' +
                ", senderId='" + senderId + '\'' +
                ", receiverId='" + receiverId + '\'' +
                '}';
    }


}
