package org.studia.barterapplication.models;

import java.util.ArrayList;
import java.util.Date;

/**
 * Post is generated by users to exchange items
 */

public class Post implements Reportable, Comparable<Post> {

    //Properties
    String title;
    String description;
    String voivodeship;
    String city;
    String id;
    int price;
    String picture;
    ArrayList<Report> reports;
    String sellerId;
    String sellerName;
    Category category;
    Date timestamp;

    //Constructors
    /**This is for firebase
     * */
    public Post() { // important do not delete this
    }


    public Post (String title, String description, String voivodeship, String city, int price, String aPicture, Category category, String sellerId, String sellerName, String id, Date timestamp) {
        this.sellerId = sellerId;
        this.sellerName = sellerName;
        this.title = title;
        this.description = description;
        this.voivodeship = voivodeship;
        this.city = city;
        this.price = price;
        this.id = id;
        picture = aPicture;
        reports = new ArrayList<>();
        this.category = category;
        this.id = id;
        this.timestamp = timestamp;
    }

    public Post (String title, String description, String voivodeship, String city, int price, String aPicture, Category category, String sellerId, String sellerName, String id, ArrayList<Report> reports, Date timestamp) {
        this.sellerId = sellerId;
        this.sellerName = sellerName;
        this.title = title;
        this.description = description;
        this.voivodeship = voivodeship;
        this.city = city;
        this.price = price;
        this.id = id;
        picture = aPicture;
        this.reports = reports;
        this.category = category;
        this.id = id;
        this.timestamp = timestamp;
    }

    //Methods
    public void deletePicture( String aPicture) {
        this.picture = "";
    }

    //accessor methods

    public String getId() {
        return id;
    }
    public String getTitle() {
        return this.title;
    }

    public String getDescription() {
        return this.description;
    }

    public String getCity() {
        return this.city;
    }

    public int getPrice() {
        return this.price;
    }

    public String getSellerId() {
        return this.sellerId;
    }

    public String getSellerName() {
        return sellerName;
    }

    public Category getCategory() {
        return category;
    }

    public String getPicture() {
        return picture;
    }

    public ArrayList<Report> getReports() {
        return reports;
    }

    public String getVoivodeship() {
        return voivodeship;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    //mutator methods

    public void setId(String id) {
        this.id = id;
    }

    public void setPicture( String aPicture) {
        this.picture = aPicture;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setVoivodeship(String voivodeship) {
        this.voivodeship = voivodeship;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public void setReports(ArrayList<Report> reports) {
        this.reports = reports;
    }

    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }



    /**
     * This method compares id's of two posts
     * @param o
     * @return true if ids are same
     */
    @Override
    public boolean equals(Object o) {

        if( o == null ){
            return false;
        }
        else if( o instanceof Post){
            Post otherPost = (Post) o;
            return this.getId().equals( otherPost.getId());
        }
        else {
            return false;
        }
    }

    /**
     * toString method for post
     * @return description, price, sellerId name and name of the category
     */
    @Override
    public String toString() {
        return this.description + " for " +  this.price + " Zł " + " by " + this.sellerId +
                "\n name of the category: " + this.category +"\n";
    }

    /**
     * This method is used to create a report about the post
     * @param description
     * @param category
     * @param ownerId
     */
   @Override
    public void report(String description, int category, String ownerId) {

        this.reports.add( new Report(description, category, ownerId) );

    }

    /**
     * This method compares prices of two posts
     * @param post
     * @return
     */
    @Override
    public int compareTo(Post post) {

        return this.getPrice() - post.getPrice();

    }

}

