package org.studia.barterapplication.models;

/**
 * Report is generated by users to notify admins of inappropriate posts
 */
public class Report {

    //Properties
    private String description;
    private int category;
    private String ownerId;

    //Constructors
    //for firebase
    public Report() {
    }

    /**Constructor to initialize description, category and owner.
     * @param description
     * @param category
     * @param ownerId
     * */
    public Report(String description, int category, String ownerId) {
        this.description = description;
        this.category = category;
        this.ownerId = ownerId;
    }

    //Methods
    // accessor methods
    public int getCategory() {
        return category;
    }

    public String getDescription() {
        return description;
    }

    public String getOwner() {
        return ownerId;
    }

    //mutator methods
    public void setDescription(String description) {
        this.description = description;
    }

    public void setCategory(int category) {
        this.category = category;
    }

    public void setOwner(String ownerId) {
        this.ownerId = ownerId;
    }



}

